spring:
  profiles:
    active: prod
  application:
    name: oa-service

eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: oa_service01:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml     # 所有的mapper映射文件
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true #延迟加载
    aggressive-lazy-loading: false
info:
  app.name: oa_service01
  build.version: 1.0-SNAPSHOT
  author: gaoyipeng

