spring:
  profiles:
    active: prod
  application:
    name: oa_frame_service
server:
  servlet:
    context-path: /oaframe

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml     # 所有的mapper映射文件
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true #延迟加载
    aggressive-lazy-loading: false

