server:
  port: 8091
spring:
  application:
    name: oa-client

feign:
  hystrix:
    enabled: true # 开启Feign熔断

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","hystrix.stream"]

eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: oa_client01:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

info:
  app.name: oa_client01
  build.version: 1.0-SNAPSHOT
  author: gaoyipeng

